In [1]:
import numpy as np
import pandas as pd
words = ['i', 'want', 'to', 'eat', 'chinese', 'food', 'lunch', 'spend']
word_cnts = np.array([2533, 927, 2417, 746, 158, 1093, 341, 278]).reshape(1, -1)
df_word_cnts = pd.DataFrame(word_cnts, columns=words)
df_word_cnts

      i  want    to  eat  chinese  food  lunch  spend
0  2533   927  2417  746      158  1093    341    278

In [2]:
# 記錄當前字與前一個字詞的存在頻率
bigram_word_cnts = [[5, 827, 0, 9, 0, 0, 0, 2], [2, 0, 608, 1, 6, 6, 5, 1], [2, 0, 4, 686, 2, 0, 6, 211],
                    [0, 0, 2, 0, 16, 2, 42, 0], [1, 0, 0, 0, 0, 82, 1, 0], [15, 0, 15, 0, 1, 4, 0, 0],
                    [2, 0, 0, 0, 0, 1, 0, 0], [1, 0, 1, 0, 0, 0, 0, 0]]

df_bigram_word_cnts = pd.DataFrame(bigram_word_cnts, columns=words, index=words)
df_bigram_word_cnts
#由上表可知當前一個字詞(列)是want的時候, 當前字詞(行)是to的頻率在文本中共有608次

          i  want   to  eat  chinese  food  lunch  spend
i         5   827    0    9        0     0      0      2
want      2     0  608    1        6     6      5      1
to        2     0    4  686        2     0      6    211
eat       0     0    2    0       16     2     42      0
chinese   1     0    0    0        0    82      1      0
food     15     0   15    0        1     4      0      0
lunch     2     0    0    0        0     1      0      0
spend     1     0    1    0        0     0      0      0

In [3]:
#請根據給出的總詞頻(df_word_cnts)與bigram模型的詞頻(df_bigram_word_cnts)計算出所有詞的配對機率(ex:p(want|i))
df_bigram_prob = df_bigram_word_cnts.copy()

for word in words:
    df_bigram_prob.loc[word, :] = df_bigram_word_cnts.loc[word, :] / df_word_cnts.loc[0, word]
 
    
df_bigram_prob

,i,want,to,eat,chinese,food,lunch,spend
i,0.001974,0.32649,0.000000,0.003553,0.000000,0.000000,0.000000,0.000790
want,0.002157,0.00000,0.655879,0.001079,0.006472,0.006472,0.005394,0.001079
to,0.000827,0.00000,0.001655,0.283823,0.000827,0.000000,0.002482,0.087298
eat,0.000000,0.00000,0.002681,0.000000,0.021448,0.002681,0.056300,0.000000
chinese,0.006329,0.00000,0.000000,0.000000,0.000000,0.518987,0.006329,0.000000
food,0.013724,0.00000,0.013724,0.000000,0.000915,0.003660,0.000000,0.000000
lunch,0.005865,0.00000,0.000000,0.000000,0.000000,0.002933,0.000000,0.000000
spend,0.003597,0.00000,0.003597,0.000000,0.000000,0.000000,0.000000,0.000000

In [18]:
#請根據已給的機率與所計算出的機率(df_bigram_prob), 試著判斷下列兩個句子哪個較為合理

# p(i|start) = 0.25
# p(chinese|want) = 0.0011
# p(food|english) = 0.5
# p(end|food) = 0.68
# P(want|start) = 0.25
# P(chinese|i) = 0.0011

s1 = "i want chinese food"
#P(s1) = P(i|start)*P(want|i)*P(english|want)*P(food|english)*P(end|food)

p1_words = s1.split(' ')

p1 = 0.25# p(i|start) = 0.25

for n in range(len(p1_words) - 1):
    p = df_bigram_prob.loc[p1_words[n], p1_words[n+1]]
    print('p('+ p1_words[n+1] + '|' + p1_words[n]+ '): '+ str(p))
    p1 = p * p1

p1 = p1 * 0.68# p(end|food) = 0.68
    
print(p1)

p(want|i): 0.32649032767469405
p(chinese|want): 0.006472491909385114
p(food|chinese): 0.5189873417721519
0.00018644361835997033

In [19]:
s2 = "want i chinese food"
p2_words = s2.split(' ')

p2 = 0.25# P(want|start) = 0.25

for n in range(len(p2_words) - 1):
    p = df_bigram_prob.loc[p2_words[n], p2_words[n+1]]
    print('p('+ p2_words[n+1] + '|' + p2_words[n]+ '): '+ str(p))
    p2 = p * p2

p2 = p2 * 0.68# p(end|food) = 0.68
    
print(p2)

p(i|want): 0.002157497303128371
p(chinese|i): 0.0
p(food|chinese): 0.5189873417721519
0.0